Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -40,4 +40,12 @@ jobs:
         working-directory: ./codebase/rdicidr-0.1.0/
       - run: npm run build
         working-directory: ./codebase/rdicidr-0.1.0/
+      - name: Check CI Pipeline Status
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "CI pipeline passed"
+          else
+            echo "CI pipeline failed"
+            exit 1
+          fi
       
